config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "searches#search"
  put '/searches/increment', to: 'searches#increment'
  put '/searches/decrement', to: 'searches#decrement'
  get '/searchers/clean', to: 'searches#clean', as: 'searches_clean'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/query.rb
class Query < ApplicationRecord
  validates :search, uniqueness: true

  before_create :normalize

  def normalize
    self.search.downcase!
    self.count = 1
  end

  def increment_count
    self.count += 1
    self.save
  end

  def decrement_count
    self.count -= 1
    self.count == 0 ? self.destroy : self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @queries = Query.all.order(count: :desc)
  end

  def increment
    perform(:increment_count)
  end

  def decrement
    perform(:decrement_count)
  end

  def clean
    Query.delete_all

    redirect_to :root
  end

  private

  def perform(action)
    QueryWorker.perform_async(search_normalized, QueryWorker::ACTIONS[action])
    render json: { status: 200 }
  end

  def search_normalized
    params[:query][:search].downcase
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <head>
    <title>Helpjuice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/queries/_query.html.erb
<query id="query-<%= query.search.gsub(' ', '--') %>">
  <query-search><%= query.search %></query-search>
  <query-count><%= query.count %></query-count>
</query>

app/views/searches/search.html.erb
<app>
  <search>
    <form>
      <input id="query" type="text" autocomplete="off" placeholder="search something..." />
    </form>
    <clean><%= link_to('Clean analytics', searches_clean_path) %></clean>
  </search>

  <queries>
    <%= render @queries %>
  </queries>
</app>